# This workflow generates translation files from code and moves the generated
# translation files to the openedx-translations repository via an auto-merged pull
# request.

name: Generate Translation Files

on:
  # This action is meant to be used from other actions.
  # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
  - workflow_call
  - workflow_dispatch

jobs:
  setup-branch:
    runs-on: ubuntu-latest
    steps:
    - name: clone Carlos-Muniz/openedx-translations
      uses: actions/checkout@v3
    - name: make and push a new branch
      run: |
        git checkout -b automated/generate-translations
        git push --set-upstream origin automated/generate-translations

  python-translations:
    strategy:
      matrix:
        repo: [credentials]
    runs-on: ubuntu-latest
    needs: [setup-branch]

    steps:
      # Clones the openedx-translations repo
      - name: clone Carlos-Muniz/openedx-translations
        uses: actions/checkout@v3
        with:
          ref: automated/generate-translations
      
      # Installs gettext, a dependency for generating translation files in django
      - name: install gettext
        run: sudo apt install -y gettext

      # Clones the  repository
      - name: clone Carlos-Muniz/${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: Carlos-Muniz/${{ matrix.repo }}
          path: ${{ matrix.repo }}

      # Sets up Python
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Installs Python requirements from translations.txt
      - name: install requirements
        run: |
          cd ${{ matrix.repo }}
          pip install -r requirements/translations.txt

      # Generates the english translation files
      - name: generate translations
        run: |
          cd ${{ matrix.repo }}
          make extract_translations
      
      # Commit only the english files
      - name: commit the english files
        run: |
          # set identity
          git config --global user.email "cmuniz@tcril.org"
          git config --global user.name "Carlos Muniz"
          # finds the directory containing the english locale usually located in
          # */*/conf/locale/en
          EN_DIR=$(find ${{matrix.repo}} -type d -name "en")
          # determine the git status
          git status -s
          # finds the django.po and djangojs.po files generated by make
          # extract_translations into EN_DIR and adds them
          DJANGO_PATH=$(find $EN_DIR -iname 'django.po')
          DJANGOJS_PATH=$(find $EN_DIR -iname 'djangojs.po')
          git add $DJANGO_PATH $DJANGOJS_PATH -v
          git status -s
          # commit the changes
          git commit -m "chore: add generated translations from ${{ matrix.repo }}"
          # push changes to branch
          git push
